//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereAmI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhereAmI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this action?.
        /// </summary>
        public static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Action.
        /// </summary>
        public static string DeleteActionTitle {
            get {
                return ResourceManager.GetString("DeleteActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this place?.
        /// </summary>
        public static string DeletePlace {
            get {
                return ResourceManager.GetString("DeletePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Place.
        /// </summary>
        public static string DeletePlaceTitle {
            get {
                return ResourceManager.GetString("DeletePlaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} is already present!.
        /// </summary>
        public static string ErrMsgNameAlreadyPresent {
            get {
                return ResourceManager.GetString("ErrMsgNameAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required!.
        /// </summary>
        public static string ErrMsgRequired {
            get {
                return ResourceManager.GetString("ErrMsgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is too long! (Max {0}).
        /// </summary>
        public static string ErrMsgStringTooLong {
            get {
                return ResourceManager.GetString("ErrMsgStringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset statistics for this place?.
        /// </summary>
        public static string ResetCntPlace {
            get {
                return ResourceManager.GetString("ResetCntPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Statistics.
        /// </summary>
        public static string ResetCntPlaceTitle {
            get {
                return ResourceManager.GetString("ResetCntPlaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds an application and adds it in my actions.
        /// </summary>
        public static string ToolTip_AddApp {
            get {
                return ResourceManager.GetString("ToolTip_AddApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for a command and adds it in my actions.
        /// </summary>
        public static string ToolTip_AddCommand {
            get {
                return ResourceManager.GetString("ToolTip_AddCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds an image to set as wallpaper and adds it in my actions.
        /// </summary>
        public static string ToolTip_AddImage {
            get {
                return ResourceManager.GetString("ToolTip_AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves this place in my places.
        /// </summary>
        public static string ToolTip_AddPlace {
            get {
                return ResourceManager.GetString("ToolTip_AddPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes this action.
        /// </summary>
        public static string ToolTip_DeleteAction {
            get {
                return ResourceManager.GetString("ToolTip_DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes this place.
        /// </summary>
        public static string ToolTip_DeletePlace {
            get {
                return ResourceManager.GetString("ToolTip_DeletePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edits parameters for this place.
        /// </summary>
        public static string ToolTip_EditPlace {
            get {
                return ResourceManager.GetString("ToolTip_EditPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizes this place between my places.
        /// </summary>
        public static string ToolTip_Refresh {
            get {
                return ResourceManager.GetString("ToolTip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets time counter for this place.
        /// </summary>
        public static string ToolTip_Reset {
            get {
                return ResourceManager.GetString("ToolTip_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the saved snapshot with the current one?.
        /// </summary>
        public static string UpdateWifiMsg {
            get {
                return ResourceManager.GetString("UpdateWifiMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Wifi Snapshot.
        /// </summary>
        public static string UpdateWifiTitle {
            get {
                return ResourceManager.GetString("UpdateWifiTitle", resourceCulture);
            }
        }
    }
}
